Apiv2 upgrade
CDRH/family_letters pull request #178
Opened 2024-11-11 19:38 UTC by wkdewey

2024-12-12 18:05 UTC, techgique requested changes

2024-12-18 22:09 UTC, wkdewey commented on app/views/layouts/head/_stylesheets.html.erb
> +  <%# include Orchid::ApplicationHelper %>
I think it may have been a mistake

2024-12-18 22:15 UTC, wkdewey commented on app/views/layouts/head/_stylesheets.html.erb
> +  <%# include Orchid::ApplicationHelper %>
I was probably trying to debug something and though I needed that include line. I'll take it out.

2024-12-18 22:48 UTC, wkdewey commented on app/views/layouts/head/_stylesheets.html.erb
> +  <%# include Orchid::ApplicationHelper %>
removed (looks like the `include` needed to be handled in config instead)

2024-12-18 22:51 UTC, wkdewey commented on config/environments/production.rb
> +  config.log_level = :warn
done

2024-12-19 16:53 UTC, techgique approved these changes

2024-12-19 16:53 UTC, merged